version: 1.0.{build}

configuration: Release

before_build:
  - nuget restore
  
build:
  publish_nuget: true
  verbosity: normal
  
after_build:
  - ps: >-
      . .\build.ps1 Pack-Nuget
      
test: off      
      
artifacts:
  - path: src\nuget\titcs.sharepoint.ssom
    name: src

deploy:
- provider: NuGet
  server: https://www.nuget.org
  api_key:
    secure: gPpssATrDRZaa6fHJn0irm9K1T4LWPuvlDrD23bN1Mbu9VA6TIogGJfoFDN/pxOD
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    
notifications:
- provider: Email
  to:
  - stiven@outlook.com
  subject: TITcs.SharePoint.SSOM Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
