version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore src/titcs.sharepoint.ssom.sln
after_build:
  - ps: >-
      . .\build.ps1 Pack-Nuget
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: gPpssATrDRZaa6fHJn0irm9K1T4LWPuvlDrD23bN1Mbu9VA6TIogGJfoFDN/pxOD
  skip_symbols: true
notifications:
- provider: Email
  to:
  - stiven@outlook.com
  subject: TITcs.SharePont.SSOM Build
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
